[package]
name = "wallswitcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
rand = "0.8.5"
ticker = "0.1.1"
tokio = { version = "1.38.0", features = ["net", "rt-multi-thread", "macros", "time", "process", "io-util"] }
